# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: .NET Core

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Oriental_Oasis_Web/Oriental_Oasis_Web.sln

    - name: Build
      run: dotnet build Oriental_Oasis_Web/Oriental_Oasis_Web.sln --configuration Release

    - name: Publish
      run: dotnet publish Oriental_Oasis_Web/Oriental_Oasis_Web.sln --configuration Release --output ./output

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: <your-app-name>
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-app
        path: ./output
