name: Build and Deploy .NET Core Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Oriental_Oasis_Web/Oriental_Oasis_Web.sln

    - name: Build
      run: dotnet build Oriental_Oasis_Web/Oriental_Oasis_Web.sln --configuration Release

    - name: Publish
      run: dotnet publish Oriental_Oasis_Web/Oriental_Oasis_Web.sln --configuration Release --output ./output

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: OrientalOasis
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./output

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-app
        path: ./output
